name: Snapshot build

on:
  push:
    branches-ignore:
      - 'release-**'

jobs:
  build_as_local:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build and Install
        id: build
        run: |
          cd sample
          ./gradlew ktlint detekt --no-daemon
          ./gradlew jacocoProjectReport --no-daemon
          ./gradlew :library:assembleDebug publishToMavenLocal --no-daemon

      - name: Doc
        id: doc
        run: |
          cd sample
          ./gradlew :library:dokkaHtml :dokkaGfmCollector --no-daemon

  build_as_remote:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build and Install
        id: build
        run: |
          cd sample
          ./gradlew -PDOLBYIO_GRADLE_VERSION_USED="$GITHUB_SHA" ktlint detekt --no-daemon
          ./gradlew -PDOLBYIO_GRADLE_VERSION_USED="$GITHUB_SHA" jacocoProjectReport --no-daemon
          ./gradlew -PDOLBYIO_GRADLE_VERSION_USED="$GITHUB_SHA" :library:assembleDebug publishToMavenLocal --no-daemon

      - name: Doc
        id: doc
        run: |
          cd sample
          ./gradlew -PDOLBYIO_GRADLE_VERSION_USED="$GITHUB_SHA" :library:dokkaHtml :dokkaGfmCollector --no-daemon

  release:
    runs-on: ubuntu-latest
    needs: [ build_as_local, build_as_remote]
    if: github.ref == 'refs/heads/main'
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - uses: ./.github/actions/version
        id: version
      
      - name: Check mandatory variables
        id: check
        run: |
          echo "${{ steps.version.outputs.configuration }}"

      - name: Create Github's master release
        id: automatic_master
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.version.outputs.configuration }}"
          prerelease: false
          title: ${{ steps.version.outputs.configuration }}
