name: Snapshot build

on:
  push:
    branches-ignore:
      - 'release-**'

jobs:
  build_as_local:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build and Install
        id: build
        run: |
          cd sample
          ./gradlew ktlint detekt :library:assembleRelease publishToMavenLocal

  build_as_remote:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build and Install
        id: build
        run: |
          cd sample
          ./gradlew -PDOLBYIO_GRADLE_VERSION_USED="$GITHUB_SHA" ktlint detekt :library:assembleDebug publishToMavenLocal
